from django.db import models
from django.contrib.auth.models import User
from django.db.models import UniqueConstraint

class modeloInicializar(models.Model):
    clave = models.CharField(primary_key=True, max_length=10)

estatusCombo = (
    ("ALTA", 'ALTA'), ("BAJA", 'BAJA')
)

condicionSelect = (
    ('7 DIAS','7 DIAS'), ("CONTADO", 'CONTADO'), ('30 DIAS','30 DIAS'), ('15 DIAS','15 DIAS')
)

causaSelect = (
    ('S01 Sin efectos fiscales','S01 Sin efectos fiscales'), ("G03 Gastos en general", 'G03 Gastos en general'), ('I03 Equipo de transporte','I03 Equipo de transporte')
)

listaPreciosEspSelect = (
    ('32','32'),('1','1')
)

unidadSelect = (
    ('PIEZA','PIEZA'),('Caja','Caja')
)

class Prov(models.Model):
    Clave = models.CharField(primary_key=True, max_length=10)
    Nombre = models.CharField(max_length=100, null=True)
    Telefono = models.CharField(max_length=100,null=True)
    Email = models.CharField(max_length=100, null=True)
    Direccion = models.CharField(max_length=100,null=True)
    CodigoPostal = models.CharField(max_length=15)
    RFC = models.CharField(max_length=15,null=False)
    Estatus = models.CharField(max_length=15,choices=estatusCombo,null=False)
    #Este metodo hace que se muestre el nombre en el admin y no se muestre proveedores object (1)
    def __str__(self):
        return self.Nombre or ''
    
class proveedoresUsuarios(models.Model):
    idProveedor = models.ForeignKey(Prov, on_delete=models.CASCADE)
    idUser = models.ForeignKey(User, on_delete=models.CASCADE)
    
class Art(models.Model):
    #--------------------------- EL CAMPO "CVE" SERIA EL ID
    Articulo = models.CharField(max_length=20, primary_key=True)
    Descripcion1 = models.CharField(max_length=1000, null=True) #--------------------------- DESCRIPCION
    Fabricante = models.CharField(max_length=50, null=True)
    Linea = models.CharField(max_length=50, null=True)
    Impuesto1 = models.FloatField(null=False) #--------------------------- IMPUESTOS IVA
    Impuesto2 = models.FloatField(null=False) #--------------------------- IMPUESTOS IVA
    Unidad = models.CharField(max_length=50, null=True)
    UnidadCompra = models.CharField(max_length=50, null=True)
    UnidadTraspaso = models.CharField(max_length=50, null=True)
    Tipo = models.CharField(max_length=20,null=False)    
    TipoOpcion = models.CharField(max_length=20,null=False)
    Accesorios = models.BooleanField(default=False,null=False)
    Refacciones = models.BooleanField(default=False,null=False)
    Sustitutos = models.BooleanField(default=False,null=False)
    Servicios = models.BooleanField(default=False,null=True)
    Consumibles = models.BooleanField(default=False,null=True)
    MonedaCosto = models.CharField(max_length=10,null=False)
    MonedaPrecio = models.CharField(max_length=10,null=False)
    PrecioLista = models.DecimalField(decimal_places=4, max_digits=8, null=True)
    Estatus = models.CharField(max_length=15,null=False)
    Conciliar = models.BooleanField(default=False,null=False)
    Refrigeracion = models.BooleanField(default=False,null=False)
    TieneCaducidad = models.BooleanField(default=False,null=False)
    BasculaPesar = models.BooleanField(default=False,null=True)
    SeProduce = models.BooleanField(default=False,null=False)
    EstatusPrecio = models.CharField(max_length=15,null=True)
    wMostrar = models.BooleanField(default=False,null=True)
    SeCompra = models.BooleanField(default=False,null=False)
    SeVende = models.BooleanField(default=False,null=False)
    EsFormula = models.BooleanField(default=False,null=False)
    ProdCantidad = models.FloatField(null=True)
    ProdUsuario = models.CharField(max_length=10,null=True)
    ProdPasoTotal = models.IntegerField(null=True)
    ProdOpciones = models.BooleanField(default=False,null=False)
    ProdVerConcentracion = models.BooleanField(default=False,null=True)
    ProdVerCostoAcumulado = models.BooleanField(default=False,null=True)
    ProdVerMerma = models.BooleanField(default=False,null=True)
    ProdVerDesperdicio = models.BooleanField(default=False,null=True)
    ProdVerPorcentaje = models.BooleanField(default=False,null=True)
    ProdMov = models.CharField(max_length=20,null=True)
    TieneMovimientos = models.BooleanField(default=False,null=True)
    EstatusCosto = models.CharField(max_length=15,null=True)
    SolicitarPrecios = models.BooleanField(blank=True, null=True)
    Espacios = models.BooleanField(blank=True, null=True)
    EspaciosEspecificos = models.BooleanField(blank=True, null=True)
    EspaciosNivel = models.CharField(max_length=50, blank=True, null=True)
    EspaciosMinutos = models.IntegerField(blank=True, null=True)
    EspaciosBloquearAnteriores = models.BooleanField(blank=True, null=True)
    SerieLoteInfo = models.BooleanField(blank=True, null=True)
    FactorCompra = models.FloatField(blank=True, null=True)    
    ISAN = models.BooleanField(blank=True, null=True)
    ExcluirDescFormaPago = models.BooleanField(blank=True, null=True)
    EsDeducible = models.BooleanField(blank=True, null=True)
    CodigoAlterno = models.CharField(blank=True, max_length=50, null=True)
    TipoCatalogo = models.CharField(max_length=20, blank=True, null=True)
    AnexosAlFacturar = models.BooleanField(blank=True, null=True)
    Actividades = models.BooleanField(blank=True, null=True)
    ValidarPresupuestoCompra = models.CharField(max_length=20, blank=True, null=True)
    SeriesLotesAutoOrden = models.CharField(max_length=20, blank=True, null=True)
    LotesFijos = models.BooleanField(blank=True, null=True)
    LotesAuto = models.BooleanField(blank=True, null=True)
    EsCombustible = models.BooleanField(blank=True, null=True)
    TieneDireccion = models.BooleanField(blank=True, null=True)
    PrecioLiberado = models.BooleanField(blank=True, null=True)
    ValidarCodigo = models.BooleanField(blank=True, null=True)
    CostoIdentificado = models.BooleanField(blank=True, null=True)
    Impuesto1Excento = models.BooleanField(blank=True, null=True)
    CalcularPresupuesto = models.BooleanField(blank=True, null=True)
    Excento2 = models.BooleanField(blank=True, null=True)
    Excento3 = models.BooleanField(blank=True, null=True)
    NivelToleranciaCosto = models.CharField(max_length=10, blank=True, null=True)
    SAUX = models.BooleanField(blank=True, null=True)
    EstibaMaxima = models.IntegerField(blank=True, null=True)
    EstibaMismaFecha = models.BooleanField(blank=True, null=True)
    PermiteEstibar = models.BooleanField(blank=True, null=True)
    EmidaRecargaTelefonica = models.BooleanField(blank=True, null=True)
    EmidaTiempoAire = models.BooleanField(blank=True, null=True)
    EsFactory = models.BooleanField(blank=True, null=True)
    FAE = models.BooleanField(default=True)
    SincroID = models.DateTimeField(blank=True, null=True)
    SincroC = models.IntegerField(blank=True, null=True)
    Sugeridos = models.BooleanField(blank=True, null=True)
    MaterialPeligroso = models.BooleanField(blank=True, null=True)
    LDI = models.BooleanField(blank=True, null=True)
    MultiploFabricacion = models.FloatField()
    MultiploConsumo = models.FloatField()
    EsMES = models.BooleanField(default=True)
    AplicaRedondeo = models.FloatField()
    Recuperacion = models.BooleanField(blank=True, null=True)
    RutaArticulo = models.BooleanField(blank=True, null=True)
    ProdRutaSecuencial = models.BooleanField(blank=True, null=True)
    CESumarizaEnFactura = models.BooleanField(blank=True, null=True)
    CENoAplicaBeca = models.BooleanField(blank=True, null=True)
    CENoAplicaPorcMat = models.BooleanField(blank=True, null=True)
    IEDU = models.BooleanField(blank=True, null=True)
    MesEnIEDU = models.BooleanField(blank=True, null=True)
    ProdEstructuraFam = models.BooleanField(blank=True, null=True)
    ImpuestosLocalesCFDI = models.BooleanField(blank=True, null=True)
    Calificacion = models.SmallIntegerField(default=0)
    CFDIRetIEPSImpuesto = models.CharField(blank=True, max_length=10, null=True)
    vicPromPlanos = models.BooleanField(blank=True, null=True)
    vicPropio = models.BooleanField(blank=True, null=True)
    vicComplemento = models.BooleanField(blank=True, null=True)
    TieneContrato = models.BooleanField(blank=True, null=True)
    PrecioVentaM2 = models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)
    MFATipoDeducibilidad = models.CharField(max_length=50)
    
    class Meta:
        unique_together = (('Articulo'),)
        ordering = ['Articulo']
        
    def __str__(self):
        return self.Articulo or ''
    
class ArtUnidad(models.Model):
    Articulo = models.ForeignKey(Art, on_delete=models.CASCADE)
    Unidad = models.CharField(max_length=50)
    Factor = models.FloatField(blank=True, null=True)

    class Meta:
        unique_together = (('Articulo', 'Unidad'),)
        
class EmpresaGrupo(models.Model):
    Grupo = models.CharField(max_length=100,primary_key=True)
    clave = models.CharField(max_length=5)

class Empresa(models.Model):
    Empresa = models.CharField(max_length=5, primary_key=True)
    Nombre = models.CharField(max_length=100, null=True, blank=True)
    Grupo = models.ForeignKey(EmpresaGrupo, on_delete=models.CASCADE, to_field='Grupo', null=True, blank=True)
    Direccion = models.CharField(max_length=100, null=True, blank=True)
    DireccionNumero = models.CharField(max_length=20, null=True, blank=True)
    DireccionNumeroInt = models.CharField(max_length=20, null=True, blank=True)
    Colonia = models.CharField(max_length=100, null=True, blank=True)
    Poblacion = models.CharField(max_length=30, null=True, blank=True)
    Estado = models.CharField(max_length=30, null=True, blank=True)
    Pais = models.CharField(max_length=30, null=True, blank=True)
    CodigoPostal = models.CharField(max_length=15, null=True, blank=True)
    Telefonos = models.CharField(max_length=100, null=True, blank=True)
    Fax = models.CharField(max_length=50, null=True, blank=True)
    Encabezado1 = models.CharField(max_length=255, null=True, blank=True)
    Encabezado2 = models.CharField(max_length=255, null=True, blank=True)
    Estatus = models.CharField(max_length=15)
    UltimoCambio = models.DateTimeField(null=True, blank=True)
    UltimaCorrida = models.DateTimeField(null=True, blank=True)
    Alta = models.DateTimeField(null=True, blank=True)
    RFC = models.CharField(max_length=20, null=True, blank=True)
    RegistroPatronal = models.CharField(max_length=20, null=True, blank=True)
    ClaveActividad = models.CharField(max_length=20, null=True, blank=True)
    Representante = models.CharField(max_length=100, null=True, blank=True)
    RepresentanteRFC = models.CharField(max_length=20, null=True, blank=True)
    RepresentanteCURP = models.CharField(max_length=20, null=True, blank=True)
    Zona = models.CharField(max_length=50, null=True, blank=True)
    Numero = models.IntegerField(null=True, blank=True)
    TieneMovimientos = models.BooleanField(null=True, blank=True)
    CambioBloquear = models.BooleanField(null=True, blank=True)
    Controladora = models.CharField(max_length=5, null=True, blank=True)
    FactorIntegracion = models.FloatField(null=True, blank=True)
    Tipo = models.CharField(max_length=20, null=True, blank=True)
    ImportadorRegimen = models.CharField(max_length=30, null=True, blank=True)
    ImportadorRegistro = models.CharField(max_length=30, null=True, blank=True)
    ImportadorFechaD = models.DateTimeField(null=True, blank=True)
    ImportadorFechaA = models.DateTimeField(null=True, blank=True)
    Delegacion = models.CharField(max_length=100, null=True, blank=True)
    GLN = models.CharField(max_length=50, null=True, blank=True)
    CFD = models.BooleanField(null=True, blank=True)
    FiscalRegimen = models.CharField(max_length=30, null=True, blank=True)
    FiscalZona = models.CharField(max_length=30, null=True, blank=True)
    Organizacion = models.IntegerField(null=True, blank=True)
    TipoRegistro = models.CharField(max_length=20, null=True, blank=True)
    IdentificacionRepresentante = models.CharField(max_length=20, null=True, blank=True)
    Contador = models.CharField(max_length=40, null=True, blank=True)
    RFCContador = models.CharField(max_length=15, null=True, blank=True)
    LongitudEstablecimiento = models.IntegerField(null=True, blank=True)
    LongitudPuntoEmision = models.IntegerField(null=True, blank=True)
    LongitudSecuencialSRI = models.IntegerField(null=True, blank=True)
    LongitudAutorizacion = models.IntegerField(null=True, blank=True)
    EcuadorRepresentanteLegal = models.CharField(max_length=40, null=True, blank=True)
    EcuadorNumeroIdentificacion = models.CharField(max_length=15, null=True, blank=True)
    EcuadorRepresentanteLegalTipo = models.CharField(max_length=20, null=True, blank=True)
    EcuadorRUCContadorTipo = models.CharField(max_length=20, null=True, blank=True)
    EsEcuador = models.BooleanField(null=True, blank=True)
    EsGuatemala = models.BooleanField(null=True, blank=True)
    GtImporteMinimoSinRetencion = models.FloatField(null=True, blank=True)
    Configuracion = models.CharField(max_length=10, null=True, blank=True)
    ReferenciaIntelisisService = models.CharField(max_length=50, null=True, blank=True)
    EmpresaLDI = models.CharField(max_length=20, null=True, blank=True)
    EFOS = models.BooleanField(null=True, blank=True)
    MapaLatitud = models.FloatField(null=True, blank=True)
    MapaLongitud = models.FloatField(null=True, blank=True)
    MapaPrecision = models.IntegerField(null=True, blank=True)
    MapaUbicacion = models.CharField(max_length=100, null=True, blank=True)
    CFD_noCertificado = models.CharField(max_length=20, null=True, blank=True)
    CFD_version = models.CharField(max_length=10, null=True, blank=True)
    CFD_versionFecha = models.DateTimeField(null=True, blank=True)
    CFD_versionAnterior = models.CharField(max_length=10, null=True, blank=True)
    CFD_EAN13 = models.CharField(max_length=20, null=True, blank=True)
    CFD_DUN14 = models.CharField(max_length=20, null=True, blank=True)
    CFD_SKU = models.CharField(max_length=20, null=True, blank=True)
    CFD_SKUCodigoInterno = models.BooleanField(null=True, blank=True)
    CFD_Llave = models.CharField(max_length=255, null=True, blank=True)
    CFD_Certificado = models.CharField(max_length=255, null=True, blank=True)
    CFD_ContrasenaSello = models.CharField(max_length=100, null=True, blank=True)
    CRMObjectId = models.UUIDField(null=True, blank=True)
    CRMLastUpdate = models.DateTimeField(null=True, blank=True)
    TipoOperacion = models.CharField(max_length=100, null=True, blank=True)
    ClavePedimento = models.CharField(max_length=100, null=True, blank=True)
    CertificadoOrigen = models.CharField(max_length=100, null=True, blank=True)
    NumCertificadoOrigen = models.CharField(max_length=50, null=True, blank=True)
    NumeroExportadorConfiable = models.CharField(max_length=50, null=True, blank=True)
    Kiosco = models.CharField(max_length=30, null=True, blank=True)
    TokenTipoCambio = models.BooleanField(null=True, blank=True)
    
    def __str__(self):
        return self.Empresa or ''
    
class Alm(models.Model):
    Almacen = models.CharField(max_length=10, primary_key=True)
    Estado = models.CharField(max_length=30, null=True, blank=True)
    def __str__(self):
        return self.Almacen or ''
    
class Venta(models.Model):
    id = models.AutoField(primary_key=True)
    IDVenta = models.IntegerField(unique=True)
    Empresa = models.CharField(max_length=5)
    Mov = models.CharField(max_length=20)
    FechaEmision = models.DateTimeField(null=True, blank=True)
    Moneda = models.CharField(max_length=10)
    TipoCambio = models.FloatField(null=True, blank=True)
    Usuario = models.CharField(max_length=10, null=True, blank=True)
    Estatus = models.CharField(max_length=15, null=True, blank=True)
    Directo = models.BooleanField(null=True, blank=True)
    Cliente = models.CharField(max_length=10)
    Almacen = models.CharField(max_length=10)
    ServicioGarantia = models.BooleanField(null=True, blank=True)
    ServicioFlotilla = models.BooleanField(null=True, blank=True)
    ServicioRampa = models.BooleanField(null=True, blank=True)
    ServicioExpress = models.BooleanField(null=True, blank=True)
    ServicioDemerito = models.BooleanField(null=True, blank=True)
    ServicioDeducible = models.BooleanField(null=True, blank=True)
    ServicioPuntual = models.BooleanField(null=True, blank=True)
    ServicioPoliza = models.CharField(max_length=20, null=True, blank=True)
    Extra = models.BooleanField(null=True, blank=True)
    Sucursal = models.IntegerField(null=True, blank=True)
    GenerarOP = models.BooleanField(null=True, blank=True)
    DesglosarImpuestos = models.BooleanField(null=True, blank=True)
    DesglosarImpuesto2 = models.BooleanField(null=True, blank=True)
    ExcluirPlaneacion = models.BooleanField(null=True, blank=True)
    ConVigencia = models.BooleanField(null=True, blank=True)
    EstaImpreso = models.BooleanField(null=True, blank=True)
    SubModulo = models.CharField(max_length=5, null=True, blank=True)
    Logico1 = models.BooleanField(null=True, blank=True)
    Logico2 = models.BooleanField(null=True, blank=True)
    Logico3 = models.BooleanField(null=True, blank=True)
    Logico4 = models.BooleanField(null=True, blank=True)
    EspacioResultado = models.BooleanField(null=True, blank=True)
    DineroConciliado = models.BooleanField(null=True, blank=True)
    Extra1 = models.BooleanField(null=True, blank=True)
    Extra2 = models.BooleanField(null=True, blank=True)
    Extra3 = models.BooleanField(null=True, blank=True)
    Reabastecido = models.BooleanField(null=True, blank=True)
    AF = models.BooleanField(null=True, blank=True)
    FordVisitoOASIS = models.BooleanField(null=True, blank=True)
    TieneTasaEsp = models.BooleanField(null=True, blank=True)
    DerechoDevolucion = models.BooleanField(null=True, blank=True)
    Comprobante = models.BooleanField(null=True, blank=True)
    Refacturado = models.BooleanField(null=True, blank=True)
    POSRedondeoVerif = models.BooleanField(null=True, blank=True)
    SincroID = models.DateTimeField(null=True, blank=True)
    SincroC = models.IntegerField(null=True, blank=True)
    SucursalOrigen = models.IntegerField(null=True, blank=True)
    AnticipoFacturadoTipoServicio = models.BooleanField(null=True, blank=True)
    CFDTimbrado = models.BooleanField(null=True, blank=True)
    CrossDocking = models.BooleanField(null=True, blank=True)
    FacDesgloseIVA = models.BooleanField(null=True, blank=True)
    RedimePuntos = models.BooleanField(null=True, blank=True)
    EsCancelacionFactura = models.BooleanField(null=True, blank=True)
    EsSaldoInicial = models.BooleanField(null=True, blank=True)
    vicGeneradoPorPN = models.BooleanField(null=True, blank=True)
    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['id', 'IDVenta'], name='priVenta')
        ]
        
class VentaD(models.Model):
    IDVentaD = models.ForeignKey(Venta, on_delete=models.CASCADE, to_field='IDVenta')
    Renglon = models.FloatField()
    RenglonSub = models.IntegerField()
    RenglonID = models.IntegerField(null=True, blank=True)
    RenglonTipo = models.CharField(max_length=1, null=True, blank=True)
    Cantidad = models.FloatField(null=True, blank=True)
    Almacen = models.CharField(max_length=10, null=True, blank=True)
    Articulo = models.CharField(max_length=20)
    Unidad = models.CharField(max_length=50, null=True, blank=True)
    Factor = models.FloatField(null=True, blank=True)
    CantidadInventario = models.FloatField(null=True, blank=True)
    Sucursal = models.IntegerField()
    SucursalOrigen = models.IntegerField(null=True, blank=True)
    ExcluirPlaneacion = models.BooleanField(null=True, blank=True)
    Anexo = models.BooleanField(null=True, blank=True)
    PresupuestoEsp = models.BooleanField(null=True, blank=True)
    DerechoDevolucion = models.BooleanField(null=True, blank=True)
    Comprobante = models.BooleanField(null=True, blank=True)
    ExcluirISAN = models.BooleanField(null=True, blank=True)
    Impuesto2 = models.FloatField(null=True, blank=True)
    RowNumber = models.IntegerField(null=True, blank=True)
    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['id'], name='priVentaD')
        ]
        
class Canal(models.Model):
    Nombre = models.CharField(max_length=50,null=True, blank=True)
    def __str__(self):
        return self.Nombre or ''
    
class CatalogoAjuste(models.Model):
    Tipo = models.CharField(max_length=50)
    
class Metas(models.Model):
    Articulo = models.ForeignKey(Art, on_delete=models.CASCADE)
    Proveedor = models.ForeignKey(Prov, on_delete=models.CASCADE)
    Canal = models.ForeignKey(Canal, on_delete=models.CASCADE,null=True, blank=True)
    FechaInicio = models.DateTimeField(null=True, blank=True)
    FechaFin = models.DateTimeField(null=True, blank=True)
    Apoyo = models.FloatField(null=True, blank=True)
    Promos = models.FloatField(null=True, blank=True)
    Cajas = models.FloatField(null=True, blank=True)
    Inversion = models.FloatField(null=True, blank=True)
    PromoPrecio = models.FloatField(null=True)
    Descuento = models.FloatField(null=True, blank=True)
    Caja9Litros = models.FloatField(null=True, blank=True)
    CatalogoAjuste = models.ForeignKey(CatalogoAjuste, on_delete=models.CASCADE)
    
class Sucursal(models.Model):
    Sucursal = models.IntegerField(primary_key=True)
    Nombre = models.CharField(max_length=100, null=True)
    Prefijo = models.CharField(max_length=5, null=True)
    Relacion = models.CharField(max_length=20)
    Direccion = models.CharField(max_length=100, null=True)
    DireccionNumero = models.CharField(max_length=20, null=True)
    DireccionNumeroInt = models.CharField(max_length=20, null=True)
    Delegacion = models.CharField(max_length=100, null=True)
    GLN = models.CharField(max_length=50, null=True)
    Colonia = models.CharField(max_length=100, null=True)
    Poblacion = models.CharField(max_length=30, null=True)
    Estado = models.CharField(max_length=30, null=True)
    Pais = models.CharField(max_length=100, null=True)
    CodigoPostal = models.CharField(max_length=15, null=True)
    Telefonos = models.CharField(max_length=100, null=True)
    Fax = models.CharField(max_length=50, null=True)
    Estatus = models.CharField(max_length=15)
    UltimoCambio = models.DateTimeField(null=True)
    RFC = models.CharField(max_length=20, null=True)
    RegistroPatronal = models.CharField(max_length=20, null=True)
    Encargado = models.CharField(max_length=100, null=True)
    Alta = models.DateTimeField(null=True)
    Region = models.CharField(max_length=50, null=True)
    CentralRegional = models.BooleanField(null=True)
    EnLinea = models.BooleanField(null=True)
    SucursalPrincipal = models.IntegerField(null=True)
    ListaPreciosEsp = models.CharField(max_length=20, null=True)
    Cajeros = models.BooleanField(null=True)
    CentroCostos = models.CharField(max_length=20, null=True)
    OperacionContinua = models.BooleanField(null=True)
    ZonaEconomica = models.CharField(max_length=30, null=True)
    Grupo = models.CharField(max_length=50, null=True)
    AlmacenPrincipal = models.CharField(max_length=10, null=True)
    Servidor = models.CharField(max_length=50, null=True)
    BaseDatos = models.CharField(max_length=50, null=True)
    Usuario = models.CharField(max_length=10, null=True)
    ZonaImpuesto = models.CharField(max_length=30, null=True)
    CajaCentral = models.CharField(max_length=10, null=True)
    wMovVentas = models.CharField(max_length=20, null=True)
    wAlmacen = models.CharField(max_length=10, null=True)
    wAgente = models.CharField(max_length=10, null=True)
    wUsuario = models.CharField(max_length=10, null=True)
    wUEN = models.IntegerField(null=True)
    wConcepto = models.CharField(max_length=50, null=True)
    CRTipoCredito = models.CharField(max_length=20, null=True)
    Cliente = models.CharField(max_length=10, null=True)
    Categoria = models.CharField(max_length=50, null=True)
    Acreedor = models.CharField(max_length=10, null=True)
    LocalidadCNBV = models.CharField(max_length=10, null=True)
    Tipo = models.CharField(max_length=50, null=True)
    FechaApertura = models.DateTimeField(null=True)
    VencimientoContrato = models.DateTimeField(null=True)
    Metros = models.FloatField(null=True)
    CostoBase = models.CharField(max_length=50, null=True)
    UltimaSincronizacion = models.DateTimeField(null=True)
    IP = models.CharField(max_length=20, null=True)
    IPDinamica = models.BooleanField(null=True)
    IPPuerto = models.IntegerField(null=True)
    ComunicacionEncriptada = models.BooleanField(null=True)
    MapaLatitud = models.FloatField(null=True)
    MapaLongitud = models.FloatField(null=True)
    MapaPrecision = models.IntegerField(null=True)
    MapaUbicacion = models.CharField(max_length=100, null=True)
    BloquearCobroTarjeta = models.BooleanField(null=True)
    FiscalRegimen = models.CharField(max_length=30, null=True)
    FiscalZona = models.CharField(max_length=30, null=True)
    CFDFlex = models.BooleanField(null=True)
    noCertificado = models.CharField(max_length=20, null=True)
    Llave = models.CharField(max_length=255, null=True)
    ContrasenaSello = models.CharField(max_length=100, null=True)
    CertificadoBase64 = models.TextField(null=True)
    RutaCertificado = models.CharField(max_length=255, null=True)
    ReferenciaIntelisisService = models.CharField(max_length=30, null=True)
    SucursalLDI = models.CharField(max_length=20, null=True)
    eCommerce = models.BooleanField(null=True)
    eCommerceOffLine = models.BooleanField(null=True)
    eCommerceSucursal = models.CharField(max_length=10, null=True)
    eCommerceImagenes = models.CharField(max_length=50, null=True)
    eCommerceAlmacen = models.CharField(max_length=10, null=True)
    eCommerceListaPrecios = models.CharField(max_length=20, null=True)
    eCommercePedido = models.CharField(max_length=20, null=True)
    eCommerceEstrategiaDescuento = models.CharField(max_length=20, null=True)
    eCommerceArticuloFlete = models.CharField(max_length=20, null=True)
    eCommerceTipoConsecutivo = models.CharField(max_length=20, null=True)
    eCommerceCondicion = models.CharField(max_length=50, null=True)
    eCommerceCajero = models.CharField(max_length=10, null=True)
    eCommerceCteCat = models.CharField(max_length=50, null=True)
    eCommerceAgente = models.CharField(max_length=10, null=True)
    eCommerceSincroniza = models.BooleanField(null=True)
    eCommerceImpuestoIncluido = models.BooleanField(null=True)
    POSMensajeLimiteCaja = models.BooleanField(null=True)
    HOST = models.CharField(max_length=20, null=True)
    POSLimiteCaja = models.FloatField(null=True)
    ParamAccDirIntelisisMES = models.CharField(max_length=255, null=True)
    PosOmniAlmacen = models.BooleanField(null=True)
    PosPaisOrigenSuc = models.CharField(max_length=100, null=True)
    PosCteTipo = models.CharField(max_length=15, null=True)
    PosCteTipoOtro = models.CharField(max_length=15, null=True)
    POSLimiteCaja2 = models.FloatField(null=True)
    POSCteGrupo = models.CharField(max_length=50, null=True)
    POSCteMoneda = models.CharField(max_length=10, null=True)
    eCommerceTipoConsecutivoFact = models.CharField(max_length=20, null=True)
    PinPadUsuario = models.CharField(max_length=50, null=True)
    PinPadContrasena = models.CharField(max_length=50, null=True)
    PinPadMoneda = models.CharField(max_length=50, null=True)
    eCommerceConsultaExistencias = models.BooleanField(null=True)
    eCommerceURL = models.CharField(max_length=100, null=True)
    eCommerceEnvolturaOmision = models.IntegerField(null=True)
    eCommerceCRModo = models.CharField(max_length=20, null=True)
    eCommerceCRArticulo = models.CharField(max_length=20, null=True)
    eCommerceCRArticuloAplica = models.CharField(max_length=20, null=True)
    eCommerceCRMinimo = models.FloatField(null=True)
    eCommerceCRMaximo = models.FloatField(null=True)
    eCommerceCRTipo = models.CharField(max_length=50, null=True)
    eCommerceCRConcepto = models.CharField(max_length=50, null=True)
    EnviaCorreo = models.BooleanField(null=True)
    Perfil = models.CharField(max_length=20, null=True)
    Remitente = models.CharField(max_length=255, null=True)
    BDMES = models.CharField(max_length=50, null=True)
    Directora = models.CharField(max_length=10, null=True)
    Supervisor = models.CharField(max_length=100, null=True)
    JefeSector = models.CharField(max_length=100, null=True)
    Sector = models.CharField(max_length=10, null=True)
    Zona = models.CharField(max_length=10, null=True)
    DireccionServicio = models.CharField(max_length=255, null=True)
    DifHorariaVerano = models.FloatField(null=True)
    DifHorariaInvierno = models.FloatField(null=True)
    WhatsAppCta = models.CharField(max_length=50, null=True)
    def __str__(self):
        return self.Nombre or ''
    
class ArtExistenciaNeta(models.Model):
    id = models.AutoField(primary_key=True)
    Empresa = models.CharField(max_length=5)
    Articulo = models.CharField(max_length=20)
    Almacen = models.CharField(max_length=10, null=False)
    Moneda = models.CharField(max_length=10, null=False)
    Existencia = models.FloatField()
    EmpresaArticuloAlmacen = models.CharField(max_length=100)
    
    class Meta:
        constraints = [
            UniqueConstraint(
                fields=['Empresa', 'Articulo', 'Almacen'],
                name='Empresa_Articulo_Almacen'
            )
        ]

    def __str__(self):
        return f"{self.Empresa} - {self.Articulo} - {self.Almacen}"
    
class ArtExistenciaMaquillada(models.Model):
    id = models.AutoField(primary_key=True)
    Empresa = models.CharField(max_length=5)
    Articulo = models.CharField(max_length=20)
    Almacen = models.CharField(max_length=10, null=False)
    Moneda = models.CharField(max_length=10, null=False)
    Existencia = models.FloatField()
    
class Cte(models.Model):
    Cliente = models.CharField(max_length=10, primary_key=True)
    Nombre = models.CharField(max_length=250, null=True, blank=True)
    NombreCorto = models.CharField(max_length=20, null=True, blank=True)
    Direccion = models.CharField(max_length=100, null=True, blank=True)
    DireccionNumero = models.CharField(max_length=20, null=True, blank=True)
    DireccionNumeroInt = models.CharField(max_length=20, null=True, blank=True)
    EntreCalles = models.CharField(max_length=100, null=True, blank=True)
    Plano = models.CharField(max_length=15, null=True, blank=True)
    Observaciones = models.CharField(max_length=100, null=True, blank=True)
    Delegacion = models.CharField(max_length=100, null=True, blank=True)
    Colonia = models.CharField(max_length=100, null=True, blank=True)
    Poblacion = models.CharField(max_length=100, null=True, blank=True)
    Estado = models.CharField(max_length=30, null=True, blank=True)
    Pais = models.CharField(max_length=100, null=True, blank=True)
    CodigoPostal = models.CharField(max_length=15, null=True, blank=True)
    RFC = models.CharField(max_length=15, null=True, blank=True)
    PedirTono = models.BooleanField()
    eMail1 = models.CharField(max_length=50, null=True, blank=True)
    eMail2 = models.CharField(max_length=50, null=True, blank=True)
    Categoria = models.CharField(max_length=50, null=True, blank=True)
    Grupo = models.CharField(max_length=50, null=True, blank=True)
    Familia = models.CharField(max_length=50, null=True, blank=True)
    Credito = models.CharField(max_length=50, null=True, blank=True)
    PedidosParciales = models.BooleanField()
    Tipo = models.CharField(max_length=15, null=True, blank=True)
    Agente = models.CharField(max_length=10, null=True, blank=True)
    Condicion = models.CharField(max_length=50, null=True, blank=True)
    Ruta = models.CharField(max_length=50, null=True, blank=True)
    ListaPrecios = models.IntegerField(null=True, blank=True)
    ListaPreciosEsp = models.CharField(max_length=20, null=True, blank=True)
    DefMoneda = models.CharField(max_length=10, null=True, blank=True)
    VtasConsignacion = models.BooleanField()
    Estatus = models.CharField(max_length=15, null=True)
    Conciliar = models.BooleanField()
    wVerDisponible = models.BooleanField(null=True, blank=True)
    wVerArtListaPreciosEsp = models.BooleanField(null=True, blank=True)
    ChecarCredito = models.CharField(max_length=20, null=True, blank=True)
    BloquearMorosos = models.CharField(max_length=20, null=True, blank=True)
    ModificarVencimiento = models.CharField(max_length=10, null=True, blank=True)
    CreditoEspecial = models.BooleanField()
    CreditoConLimite = models.BooleanField()
    CreditoLimite = models.DecimalField(max_digits=19, decimal_places=4, null=True, blank=True)
    CreditoConLimitePedidos = models.BooleanField(null=True, blank=True)
    CreditoMoneda = models.CharField(max_length=10, null=True, blank=True)
    CreditoConDias = models.BooleanField()
    CreditoDias = models.IntegerField(null=True, blank=True)
    CreditoConCondiciones = models.BooleanField()
    TieneMovimientos = models.BooleanField(null=True, blank=True)
    DescuentoRecargos = models.BooleanField(null=True, blank=True)
    RecorrerVencimiento = models.CharField(max_length=20, null=True, blank=True)
    AlmacenDef = models.CharField(max_length=10, null=True, blank=True)
    BonificacionTipo = models.CharField(max_length=20, null=True, blank=True)
    Descripcion1 = models.CharField(max_length=50, null=True, blank=True)
    Descripcion2 = models.CharField(max_length=50, null=True, blank=True)
    Descripcion3 = models.CharField(max_length=50, null=True, blank=True)
    Descripcion4 = models.CharField(max_length=50, null=True, blank=True)
    FormasPagoRestringidas = models.BooleanField(null=True, blank=True)
    PreciosInferioresMinimo = models.BooleanField(null=True, blank=True)
    PersonalSMS = models.BooleanField(null=True, blank=True)    
    Fuma = models.BooleanField(null=True, blank=True)
    DeducibleMoneda = models.CharField(max_length=10, null=True, blank=True)
    Flotilla = models.BooleanField(null=True, blank=True)
    ExcentoISAN = models.BooleanField(null=True, blank=True)
    EsProveedor = models.BooleanField(null=True, blank=True)
    EsPersonal = models.BooleanField(null=True, blank=True)
    EsAgente = models.BooleanField(null=True, blank=True)
    EsAlmacen = models.BooleanField(null=True, blank=True)
    EsEspacio = models.BooleanField(null=True, blank=True)
    EsCentroCostos = models.BooleanField(null=True, blank=True)
    EsProyecto = models.BooleanField(null=True, blank=True)
    EsCentroTrabajo = models.BooleanField(null=True, blank=True)
    EsEstacionTrabajo = models.BooleanField(null=True, blank=True)
    Usuario = models.CharField(max_length=10, null=True, blank=True)
    Cuenta = models.CharField(max_length=20, null=True, blank=True)
    FiscalRegimen = models.CharField(max_length=30, null=True, blank=True)
    PedidoDef = models.BooleanField(null=True, blank=True)
    eMailAuto = models.BooleanField(null=True, blank=True)
    Intercompania = models.BooleanField(null=True, blank=True)
    Publico = models.BooleanField(null=True, blank=True)
    CRMovVenta = models.CharField(max_length=20, null=True, blank=True)
    Extranjero = models.BooleanField(null=True, blank=True)
    DocumentacionCompleta = models.BooleanField(null=True, blank=True)
    Comentarios = models.TextField(null=True, blank=True)
    FueraLinea = models.BooleanField(null=True, blank=True)
    FiscalGenerar = models.BooleanField(null=True, blank=True)
    ContactoTipo = models.CharField(max_length=20, null=True, blank=True)
    TarimasChep = models.BooleanField(null=True, blank=True)
    SincronizarCRM = models.BooleanField(null=True, blank=True)
    AccesoWeb = models.BooleanField(null=True, blank=True)
    SincroC = models.IntegerField(null=True, blank=True)
    CuentaAnticipo = models.CharField(max_length=20, null=True, blank=True)
    MovimientoUltimoCobro = models.CharField(max_length=50, null=True, blank=True)
    MovimientoUltimoCobroAux = models.CharField(max_length=50, null=True, blank=True)
    CalculoMoratorioMAVI = models.BooleanField(null=True, blank=True)
    vic_NoValidarContrato = models.BooleanField(null=True, blank=True)
    MFATipoOperacion = models.CharField(max_length=50, null=True, blank=True)
    Embarazo = models.BooleanField(null=True, blank=True)
    def __str__(self):
        return self.Nombre or ''
    
class Mov(models.Model):
    Empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, to_field='Empresa')
    Modulo = models.CharField(max_length=5)
    ID = models.IntegerField(primary_key=True,null=False)
    Mov = models.CharField(max_length=20)
    MovID = models.CharField(max_length=20, null=True, blank=True)
    Ejercicio = models.IntegerField()
    Periodo = models.IntegerField()
    FechaRegistro = models.DateTimeField()
    FechaEmision = models.DateTimeField()
    Concepto = models.CharField(max_length=50, null=True, blank=True)
    Usuario = models.CharField(max_length=10, null=True, blank=True)
    Sucursal = models.ForeignKey(Sucursal, on_delete=models.CASCADE, to_field='Sucursal')
    RowNumber = models.IntegerField(null=True, blank=True)
    
class VentaTCalc(models.Model):
    ID = models.AutoField(primary_key=True, null=False)
    Empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, to_field='Empresa')
    SucursalOrigen = models.CharField(max_length=255)
    SucursalVenta = models.CharField(max_length=255, null=True, blank=True)
    Sucursal = models.ForeignKey(Sucursal, on_delete=models.CASCADE, to_field='Sucursal')
    MovID = models.CharField(max_length=20,null=True, blank=True)
    Mov = models.ForeignKey(Mov,on_delete=models.CASCADE,max_length=20, null=True)
    Moneda = models.CharField(max_length=10, null=False)
    TipoCambio = models.FloatField(null=True, blank=True)
    Concepto = models.CharField(max_length=50,null=True, blank=True)
    Referencia = models.CharField(max_length=50,null=True, blank=True)
    Proyecto = models.CharField(max_length=50,null=True, blank=True)
    FechaRegistro = models.DateTimeField(null=True, blank=True)
    FechaEmision = models.DateTimeField(null=True, blank=True)
    FechaRequerida = models.DateTimeField(null=True, blank=True)
    HoraRequerida = models.CharField(max_length=5,null=True, blank=True)
    FechaOriginal = models.DateTimeField(null=True, blank=True)
    Prioridad = models.CharField(max_length=10,null=True, blank=True)
    Estatus = models.CharField(max_length=15,null=True, blank=True)
    Situacion = models.CharField(max_length=50,null=True, blank=True)
    SituacionFecha = models.DateTimeField(null=True, blank=True)
    SituacionUsuario = models.CharField(max_length=10,null=True, blank=True)
    SituacionNota = models.CharField(max_length=100,null=True, blank=True)
    Cliente = models.ForeignKey(Cte, on_delete=models.CASCADE,max_length=10, null=False)
    ClienteNombre = models.CharField(max_length=250,null=True, blank=True)
    NombreComercial = models.CharField(max_length=100,null=True, blank=True)
    EnviarA = models.IntegerField(null=True, blank=True)
    SusursalEnviarA = models.CharField(max_length=100,null=True, blank=True)
    Agente = models.CharField(max_length=10,null=True, blank=True)
    FormaEnvio = models.CharField(max_length=50,null=True, blank=True)
    Condicion = models.CharField(max_length=50,null=True, blank=True,choices=condicionSelect)
    Vencimiento = models.DateTimeField(null=True, blank=True)
    Usuario = models.CharField(max_length=10,null=True, blank=True)
    Paquetes = models.IntegerField(null=True, blank=True)
    Observaciones = models.CharField(max_length=100,null=True, blank=True)
    Causa = models.CharField(max_length=50,null=True, blank=True, choices=causaSelect)
    AnticiposFacturados = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    Retencion = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    Ejercicio = models.IntegerField(null=True, blank=True)
    Periodo = models.IntegerField(null=True, blank=True)
    FechaConclusion = models.DateTimeField(null=True, blank=True)
    FechaEntrega = models.DateTimeField(null=True, blank=True)
    EmbarqueEstado = models.CharField(max_length=50,null=True, blank=True)
    Peso = models.FloatField(null=True, blank=True)
    Volumen = models.FloatField(null=True, blank=True)
    ListaPreciosEsp = models.CharField(max_length=20,null=True, blank=True, choices=listaPreciosEspSelect)
    ZonaImpuesto = models.CharField(max_length=30,null=True, blank=True)
    Extra = models.BooleanField(null=False, blank=True)
    ServicioArticulo = models.CharField(max_length=20,null=True, blank=True)
    ServicioSerie = models.CharField(max_length=50,null=True, blank=True)
    Clase = models.CharField(max_length=50,null=True, blank=True)
    SubClase = models.CharField(max_length=50,null=True, blank=True)
    Aplica = models.CharField(max_length=20,null=True, blank=True)
    AplicaID = models.CharField(max_length=20,null=True, blank=True)
    Renglon = models.FloatField(null=False)
    RenglonSub = models.IntegerField(null=False)
    RenglonID = models.IntegerField(null=True, blank=True)
    RenglonTipo = models.CharField(max_length=1,null=True, blank=True)
    Almacen = models.ForeignKey(Alm,on_delete=models.CASCADE,null=True)
    Codigo = models.CharField(max_length=30,null=True, blank=True)
    Articulo = models.ForeignKey(Art,on_delete=models.CASCADE,null=False)
    ArticuloNombre = models.CharField(max_length=1000,null=True, blank=True)
    ClasificacionIEPS = models.CharField(max_length=20,null=True, blank=True)
    Mililitro = models.CharField(max_length=50,null=True, blank=True)
    ProvInventario = models.CharField(max_length=50,null=True, blank=True)
    PaisOrigen = models.CharField(max_length=50,null=True, blank=True)
    SubCuenta = models.CharField(max_length=50,null=True, blank=True)
    Unidad = models.CharField(max_length=50,null=True, blank=True,choices=unidadSelect)
    Precio = models.FloatField(null=True, blank=True)
    DescuentoTipo = models.BooleanField(null=True, blank=True)
    DescuentoLinea = models.FloatField(null=True, blank=True)
    Impuesto1 = models.FloatField(null=True, blank=True)
    Impuesto2 = models.FloatField(null=True, blank=True)
    Impuesto3 = models.FloatField(null=True, blank=True)
    Cantidad = models.FloatField(null=True, blank=True)
    CantidadInventario = models.FloatField(null=True, blank=True)
    Factor = models.FloatField(null=True, blank=True)
    CantidadNeta = models.FloatField(null=True, blank=True)
    CantidadFactor = models.FloatField(null=True, blank=True)
    ReservadaFactor = models.FloatField(null=True, blank=True)
    OrdenadaFactor = models.FloatField(null=True, blank=True)
    PendienteFactor = models.FloatField(null=True, blank=True)
    ImpuestosPorcentaje = models.FloatField(null=True, blank=True)
    PoliticaPrecios = models.CharField(max_length=255,null=True, blank=True)
    Comision = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    CantidadPendiente = models.FloatField(null=True, blank=True)
    CantidadReservada = models.FloatField(null=True, blank=True)
    CantidadOrdenada = models.FloatField(null=True, blank=True)
    CantidadEmbarcada = models.FloatField(null=True, blank=True)
    Costo = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    AjusteCosteo = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    CostoUEPS = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    CostoPEPS = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    UltimoCosto = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    CostoEstandar = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    PrecioLista = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    CostoTotal = models.FloatField(null=True, blank=True)
    CostoActividad = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    CostoActividadTotal = models.FloatField(null=True, blank=True)
    PrecioTotal = models.FloatField(null=True, blank=True)
    Importe = models.FloatField(null=True, blank=True)
    ContUso = models.CharField(max_length=20,null=True, blank=True)
    ContUso2 = models.CharField(max_length=20,null=True, blank=True)
    ContUso3 = models.CharField(max_length=20,null=True, blank=True)
    Espacio = models.CharField(max_length=10,null=True, blank=True)
    UEN = models.IntegerField(null=True, blank=True)
    ExcluirISAN = models.BooleanField(null=True, blank=True)
    Posicion = models.CharField(max_length=10,null=True, blank=True)
    PresupuestoEsp = models.BooleanField(null=True, blank=True)
    DescuentoLineal = models.FloatField(null=True, blank=True)
    TipoImpuesto1 = models.CharField(max_length=10,null=True, blank=True)
    TipoImpuesto2 = models.CharField(max_length=10,null=True, blank=True)
    TipoImpuesto3 = models.CharField(max_length=10,null=True, blank=True)
    Retencion1 = models.FloatField(null=True, blank=True)
    Retencion2 = models.FloatField(null=True, blank=True)
    Retencion3 = models.FloatField(null=True, blank=True)
    FAEPorcentaje = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    CostoPromedio = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    CostoReposicion = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    Ordencompra = models.CharField(max_length=20,null=True, blank=True)
    DescripcionExtra = models.CharField(max_length=100,null=True, blank=True)
    AnticipoFacturado = models.BooleanField(null=True, blank=True)
    AnticipoMoneda = models.CharField(max_length=10,null=True, blank=True)
    AnticipoTipoCambio = models.FloatField(null=True, blank=True)
    AnticipoRetencion = models.FloatField(null=True, blank=True)
    ImpIncPrecio = models.FloatField(null=True, blank=True)
    ImpIncPreImporte = models.FloatField(null=True, blank=True)
    ImpIncImporte = models.FloatField(null=True, blank=True)
    Tarima = models.CharField(max_length=20,null=True, blank=True)
    ImpIncDescuentoLineal = models.FloatField(null=True, blank=True)
    PrecioSinDL = models.FloatField(null=True, blank=True)
    PreImporteSinDL = models.FloatField(null=True, blank=True)
    ImporteSinDL = models.FloatField(null=True, blank=True)
    DescuentoLinealSinDL = models.FloatField(null=True, blank=True)
    ImporteDescuentoGlobal = models.FloatField(null=True, blank=True)
    DescuentosTotales = models.FloatField(null=True, blank=True)
    ImpIncDescuentosTotales = models.FloatField(null=True, blank=True)
    DescuentosTotalesSinDL = models.FloatField(null=True, blank=True)
    ImporteSobrePrecio = models.FloatField(null=True, blank=True)
    SubTotal = models.FloatField(null=True, blank=True)
    SubTotalSinDL = models.FloatField(null=True, blank=True)
    ImpIncSubTotal = models.FloatField(null=True, blank=True)
    Impuesto1Total = models.FloatField(null=True, blank=True)
    Impuesto2Total = models.FloatField(null=True, blank=True)
    Impuesto3Total = models.FloatField(null=False, blank=True)
    Impuestos = models.FloatField(null=True, blank=True)
    Retencion1Total = models.FloatField(null=True, blank=True)
    Retencion2Total = models.FloatField(null=True, blank=True)
    Retencion3Total = models.FloatField(null=True, blank=True)
    FAETotal = models.FloatField(null=True, blank=True)
    ImporteTotal = models.FloatField(null=True, blank=True)
    TotalNeto = models.FloatField(null=True, blank=True)

class CompraTCalc(models.Model):
    Empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, to_field='Empresa')
    Sucursal = models.ForeignKey(Sucursal, on_delete=models.CASCADE, to_field='Sucursal')
    MovID = models.CharField(max_length=20,null=True, blank=True)
    FechaEmision = models.DateTimeField(null=True, blank=True)
    Estatus = models.CharField(max_length=15,null=False)
    Proveedor = models.ForeignKey(Prov, on_delete=models.CASCADE)
    Observaciones = models.CharField(max_length=100, null=True, blank=True)
    Renglon = models.DecimalField(max_digits=10, decimal_places=2)
    Articulo = models.ForeignKey(Art, on_delete=models.CASCADE, to_field='Articulo')
    UNIDAD_CHOICES = [
        ('pieza', 'Pieza'),
        ('caja', 'Caja'),
    ]
    Unidad = models.CharField(max_length=10, choices=UNIDAD_CHOICES)
    Costo = models.DecimalField(max_digits=10, decimal_places=2)
    CantidadNeta = models.DecimalField(max_digits=10, decimal_places=2)
    
class VentaTCalcMaquillado(models.Model):
    ID = models.AutoField(primary_key=True, null=False)
    Empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, to_field='Empresa')
    SucursalOrigen = models.CharField(max_length=255)
    SucursalVenta = models.CharField(max_length=255, null=True, blank=True)
    Sucursal = models.ForeignKey(Sucursal, on_delete=models.CASCADE, to_field='Sucursal')
    MovID = models.CharField(max_length=20,null=True, blank=True)
    Mov = models.ForeignKey(Mov,on_delete=models.CASCADE,max_length=20, null=True)
    Moneda = models.CharField(max_length=10, null=False)
    TipoCambio = models.FloatField(null=True, blank=True)
    Concepto = models.CharField(max_length=50,null=True, blank=True)
    Referencia = models.CharField(max_length=50,null=True, blank=True)
    Proyecto = models.CharField(max_length=50,null=True, blank=True)
    FechaRegistro = models.DateTimeField(null=True, blank=True)
    FechaEmision = models.DateTimeField(null=True, blank=True)
    FechaRequerida = models.DateTimeField(null=True, blank=True)
    HoraRequerida = models.CharField(max_length=5,null=True, blank=True)
    FechaOriginal = models.DateTimeField(null=True, blank=True)
    Prioridad = models.CharField(max_length=10,null=True, blank=True)
    Estatus = models.CharField(max_length=15,null=True, blank=True)
    Situacion = models.CharField(max_length=50,null=True, blank=True)
    SituacionFecha = models.DateTimeField(null=True, blank=True)
    SituacionUsuario = models.CharField(max_length=10,null=True, blank=True)
    SituacionNota = models.CharField(max_length=100,null=True, blank=True)
    Cliente = models.ForeignKey(Cte, on_delete=models.CASCADE,max_length=10, null=False)
    ClienteNombre = models.CharField(max_length=250,null=True, blank=True)
    NombreComercial = models.CharField(max_length=100,null=True, blank=True)
    EnviarA = models.IntegerField(null=True, blank=True)
    SusursalEnviarA = models.CharField(max_length=100,null=True, blank=True)
    Agente = models.CharField(max_length=10,null=True, blank=True)
    FormaEnvio = models.CharField(max_length=50,null=True, blank=True)
    Condicion = models.CharField(max_length=50,null=True, blank=True)
    Vencimiento = models.DateTimeField(null=True, blank=True)
    Usuario = models.CharField(max_length=10,null=True, blank=True)
    Paquetes = models.IntegerField(null=True, blank=True)
    Observaciones = models.CharField(max_length=100,null=True, blank=True)
    Causa = models.CharField(max_length=50,null=True, blank=True)
    AnticiposFacturados = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    Retencion = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    Ejercicio = models.IntegerField(null=True, blank=True)
    Periodo = models.IntegerField(null=True, blank=True)
    FechaConclusion = models.DateTimeField(null=True, blank=True)
    FechaEntrega = models.DateTimeField(null=True, blank=True)
    EmbarqueEstado = models.CharField(max_length=50,null=True, blank=True)
    Peso = models.FloatField(null=True, blank=True)
    Volumen = models.FloatField(null=True, blank=True)
    ListaPreciosEsp = models.CharField(max_length=20,null=True, blank=True)
    ZonaImpuesto = models.CharField(max_length=30,null=True, blank=True)
    Extra = models.BooleanField(null=False, blank=True)
    ServicioArticulo = models.CharField(max_length=20,null=True, blank=True)
    ServicioSerie = models.CharField(max_length=50,null=True, blank=True)
    Clase = models.CharField(max_length=50,null=True, blank=True)
    SubClase = models.CharField(max_length=50,null=True, blank=True)
    Aplica = models.CharField(max_length=20,null=True, blank=True)
    AplicaID = models.CharField(max_length=20,null=True, blank=True)
    Renglon = models.FloatField(null=False)
    RenglonSub = models.IntegerField(null=False)
    RenglonID = models.IntegerField(null=True, blank=True)
    RenglonTipo = models.CharField(max_length=1,null=True, blank=True)
    Almacen = models.ForeignKey(Alm,on_delete=models.CASCADE,null=True)
    Codigo = models.CharField(max_length=30,null=True, blank=True)
    Articulo = models.ForeignKey(Art,on_delete=models.CASCADE,null=False)
    ArticuloNombre = models.CharField(max_length=1000,null=True, blank=True)
    ClasificacionIEPS = models.CharField(max_length=20,null=True, blank=True)
    Mililitro = models.CharField(max_length=50,null=True, blank=True)
    ProvInventario = models.CharField(max_length=50,null=True, blank=True)
    PaisOrigen = models.CharField(max_length=50,null=True, blank=True)
    SubCuenta = models.CharField(max_length=50,null=True, blank=True)
    Unidad = models.CharField(max_length=50,null=True, blank=True)
    Precio = models.FloatField(null=True, blank=True)
    DescuentoTipo = models.BooleanField(null=True, blank=True)
    DescuentoLinea = models.FloatField(null=True, blank=True)
    Impuesto1 = models.FloatField(null=True, blank=True)
    Impuesto2 = models.FloatField(null=True, blank=True)
    Impuesto3 = models.FloatField(null=True, blank=True)
    Cantidad = models.FloatField(null=True, blank=True)
    CantidadInventario = models.FloatField(null=True, blank=True)
    Factor = models.FloatField(null=True, blank=True)
    CantidadNeta = models.FloatField(null=True, blank=True)
    CantidadFactor = models.FloatField(null=True, blank=True)
    ReservadaFactor = models.FloatField(null=True, blank=True)
    OrdenadaFactor = models.FloatField(null=True, blank=True)
    PendienteFactor = models.FloatField(null=True, blank=True)
    ImpuestosPorcentaje = models.FloatField(null=True, blank=True)
    PoliticaPrecios = models.CharField(max_length=255,null=True, blank=True)
    Comision = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    CantidadPendiente = models.FloatField(null=True, blank=True)
    CantidadReservada = models.FloatField(null=True, blank=True)
    CantidadOrdenada = models.FloatField(null=True, blank=True)
    CantidadEmbarcada = models.FloatField(null=True, blank=True)
    Costo = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    AjusteCosteo = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    CostoUEPS = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    CostoPEPS = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    UltimoCosto = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    CostoEstandar = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    PrecioLista = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    CostoTotal = models.FloatField(null=True, blank=True)
    CostoActividad = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    CostoActividadTotal = models.FloatField(null=True, blank=True)
    PrecioTotal = models.FloatField(null=True, blank=True)
    Importe = models.FloatField(null=True, blank=True)
    ContUso = models.CharField(max_length=20,null=True, blank=True)
    ContUso2 = models.CharField(max_length=20,null=True, blank=True)
    ContUso3 = models.CharField(max_length=20,null=True, blank=True)
    Espacio = models.CharField(max_length=10,null=True, blank=True)
    UEN = models.IntegerField(null=True, blank=True)
    ExcluirISAN = models.BooleanField(null=True, blank=True)
    Posicion = models.CharField(max_length=10,null=True, blank=True)
    PresupuestoEsp = models.BooleanField(null=True, blank=True)
    DescuentoLineal = models.FloatField(null=True, blank=True)
    TipoImpuesto1 = models.CharField(max_length=10,null=True, blank=True)
    TipoImpuesto2 = models.CharField(max_length=10,null=True, blank=True)
    TipoImpuesto3 = models.CharField(max_length=10,null=True, blank=True)
    Retencion1 = models.FloatField(null=True, blank=True)
    Retencion2 = models.FloatField(null=True, blank=True)
    Retencion3 = models.FloatField(null=True, blank=True)
    FAEPorcentaje = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    CostoPromedio = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    CostoReposicion = models.DecimalField(decimal_places=4, max_digits=8,null=True, blank=True)
    Ordencompra = models.CharField(max_length=20,null=True, blank=True)
    DescripcionExtra = models.CharField(max_length=100,null=True, blank=True)
    AnticipoFacturado = models.BooleanField(null=True, blank=True)
    AnticipoMoneda = models.CharField(max_length=10,null=True, blank=True)
    AnticipoTipoCambio = models.FloatField(null=True, blank=True)
    AnticipoRetencion = models.FloatField(null=True, blank=True)
    ImpIncPrecio = models.FloatField(null=True, blank=True)
    ImpIncPreImporte = models.FloatField(null=True, blank=True)
    ImpIncImporte = models.FloatField(null=True, blank=True)
    Tarima = models.CharField(max_length=20,null=True, blank=True)
    ImpIncDescuentoLineal = models.FloatField(null=True, blank=True)
    PrecioSinDL = models.FloatField(null=True, blank=True)
    PreImporteSinDL = models.FloatField(null=True, blank=True)
    ImporteSinDL = models.FloatField(null=True, blank=True)
    DescuentoLinealSinDL = models.FloatField(null=True, blank=True)
    ImporteDescuentoGlobal = models.FloatField(null=True, blank=True)
    DescuentosTotales = models.FloatField(null=True, blank=True)
    ImpIncDescuentosTotales = models.FloatField(null=True, blank=True)
    DescuentosTotalesSinDL = models.FloatField(null=True, blank=True)
    ImporteSobrePrecio = models.FloatField(null=True, blank=True)
    SubTotal = models.FloatField(null=True, blank=True)
    SubTotalSinDL = models.FloatField(null=True, blank=True)
    ImpIncSubTotal = models.FloatField(null=True, blank=True)
    Impuesto1Total = models.FloatField(null=True, blank=True)
    Impuesto2Total = models.FloatField(null=True, blank=True)
    Impuesto3Total = models.FloatField(null=False, blank=True)
    Impuestos = models.FloatField(null=True, blank=True)
    Retencion1Total = models.FloatField(null=True, blank=True)
    Retencion2Total = models.FloatField(null=True, blank=True)
    Retencion3Total = models.FloatField(null=True, blank=True)
    FAETotal = models.FloatField(null=True, blank=True)
    ImporteTotal = models.FloatField(null=True, blank=True)
    TotalNeto = models.FloatField(null=True, blank=True)

class Estatus(models.Model):
    Estatus = models.CharField(max_length=15, null=False, blank=False)
    Nombre = models.CharField(max_length=100, null=True, blank=True)
    
class Fabricante(models.Model):
    Fabricante = models.CharField(max_length=50,null=False, blank=False)