# Generated by Django 5.0.6 on 2024-07-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0004_ventad_ventad_priventad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VentaD',
        ),
    ]
