# Generated by Django 5.0.6 on 2024-07-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0005_delete_ventad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
