# Generated by Django 5.0.6 on 2024-07-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0008_ventad_ventad_priventad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventad',
            name='IDVentaD',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
        migrations.DeleteModel(
            name='VentaD',
        ),
    ]
