# Generated by Django 5.0.6 on 2024-07-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0009_remove_ventad_idventad_delete_venta_delete_ventad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('IDVenta', models.IntegerField(unique=True)),
                ('Empresa', models.CharField(max_length=5)),
                ('Mov', models.CharField(max_length=20)),
                ('FechaEmision', models.DateTimeField(blank=True, null=True)),
                ('Moneda', models.CharField(max_length=10)),
                ('TipoCambio', models.FloatField(blank=True, null=True)),
                ('Usuario', models.CharField(blank=True, max_length=10, null=True)),
                ('Estatus', models.CharField(blank=True, max_length=15, null=True)),
                ('Directo', models.BooleanField()),
                ('Cliente', models.CharField(max_length=10)),
                ('Almacen', models.CharField(max_length=10)),
                ('ServicioGarantia', models.BooleanField()),
                ('ServicioFlotilla', models.BooleanField(blank=True, null=True)),
                ('ServicioRampa', models.BooleanField(blank=True, null=True)),
                ('ServicioExpress', models.BooleanField()),
                ('ServicioDemerito', models.BooleanField()),
                ('ServicioDeducible', models.BooleanField()),
                ('ServicioPuntual', models.BooleanField(blank=True, null=True)),
                ('ServicioPoliza', models.CharField(blank=True, max_length=20, null=True)),
                ('Extra', models.BooleanField()),
                ('Sucursal', models.IntegerField()),
                ('GenerarOP', models.BooleanField(blank=True, null=True)),
                ('DesglosarImpuestos', models.BooleanField(blank=True, null=True)),
                ('DesglosarImpuesto2', models.BooleanField(blank=True, null=True)),
                ('ExcluirPlaneacion', models.BooleanField(blank=True, null=True)),
                ('ConVigencia', models.BooleanField(blank=True, null=True)),
                ('EstaImpreso', models.BooleanField(blank=True, null=True)),
                ('SubModulo', models.CharField(blank=True, max_length=5, null=True)),
                ('Logico1', models.BooleanField()),
                ('Logico2', models.BooleanField()),
                ('Logico3', models.BooleanField()),
                ('Logico4', models.BooleanField()),
                ('EspacioResultado', models.BooleanField(blank=True, null=True)),
                ('DineroConciliado', models.BooleanField(blank=True, null=True)),
                ('Extra1', models.BooleanField()),
                ('Extra2', models.BooleanField()),
                ('Extra3', models.BooleanField()),
                ('Reabastecido', models.BooleanField(blank=True, null=True)),
                ('AF', models.BooleanField(blank=True, null=True)),
                ('FordVisitoOASIS', models.BooleanField(blank=True, null=True)),
                ('TieneTasaEsp', models.BooleanField(blank=True, null=True)),
                ('DerechoDevolucion', models.BooleanField(blank=True, null=True)),
                ('Comprobante', models.BooleanField(blank=True, null=True)),
                ('Refacturado', models.BooleanField(blank=True, null=True)),
                ('POSRedondeoVerif', models.BooleanField(blank=True, null=True)),
                ('SincroID', models.DateTimeField(blank=True, null=True)),
                ('SincroC', models.IntegerField(blank=True, null=True)),
                ('SucursalOrigen', models.IntegerField()),
                ('AnticipoFacturadoTipoServicio', models.BooleanField(blank=True, null=True)),
                ('CFDTimbrado', models.BooleanField(blank=True, null=True)),
                ('CrossDocking', models.BooleanField(blank=True, null=True)),
                ('FacDesgloseIVA', models.BooleanField()),
                ('RedimePuntos', models.BooleanField(blank=True, null=True)),
                ('EsCancelacionFactura', models.BooleanField(blank=True, null=True)),
                ('EsSaldoInicial', models.BooleanField(blank=True, null=True)),
                ('vicGeneradoPorPN', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(fields=('id', 'IDVenta'), name='priVenta'),
        ),
    ]
