# Generated by Django 5.0.6 on 2024-07-16 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0010_venta_venta_priventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDVentaD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.venta')),
                ('Renglon', models.FloatField()),
                ('RenglonSub', models.IntegerField()),
                ('RenglonID', models.IntegerField(blank=True, null=True)),
                ('RenglonTipo', models.CharField(blank=True, max_length=1, null=True)),
                ('Cantidad', models.FloatField(blank=True, null=True)),
                ('Almacen', models.CharField(blank=True, max_length=10, null=True)),
                ('Articulo', models.CharField(max_length=20)),
                ('Unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('Factor', models.FloatField(blank=True, null=True)),
                ('CantidadInventario', models.FloatField(blank=True, null=True)),
                ('Sucursal', models.IntegerField()),
                ('SucursalOrigen', models.IntegerField(blank=True, null=True)),
                ('ExcluirPlaneacion', models.BooleanField(blank=True, null=True)),
                ('Anexo', models.BooleanField(blank=True, null=True)),
                ('PresupuestoEsp', models.BooleanField(blank=True, null=True)),
                ('DerechoDevolucion', models.BooleanField(blank=True, null=True)),
                ('Comprobante', models.BooleanField(blank=True, null=True)),
                ('ExcluirISAN', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='ventad',
            constraint=models.UniqueConstraint(fields=('id',), name='priVentaD'),
        ),
    ]
