# Generated by Django 5.0.6 on 2024-07-16 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0011_ventad_ventad_priventad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventad',
            name='IDVentaD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.venta', to_field='IDVenta'),
        ),
    ]
