# Generated by Django 5.0.6 on 2024-07-17 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0012_alter_ventad_idventad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaInicio', models.DateTimeField(blank=True, null=True)),
                ('FechaFin', models.DateTimeField(blank=True, null=True)),
                ('Volumen', models.FloatField(blank=True, null=True)),
                ('Descuento', models.FloatField(max_length=50)),
                ('Precio', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('Canal', models.CharField(max_length=50)),
                ('Articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.art')),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.proveedores')),
            ],
        ),
    ]
