# Generated by Django 5.0.6 on 2024-07-18 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0013_metas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metas',
            name='Canal',
        ),
    ]
