# Generated by Django 5.0.6 on 2024-07-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0014_remove_metas_canal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
