# Generated by Django 5.0.6 on 2024-07-18 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0015_canal'),
    ]

    operations = [
        migrations.AddField(
            model_name='metas',
            name='Canal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.canal'),
            preserve_default=False,
        ),
    ]
