# Generated by Django 5.0.6 on 2024-07-19 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0016_metas_canal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Metas',
        ),
    ]
