# Generated by Django 5.0.6 on 2024-07-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0018_metas'),
    ]

    operations = [
        migrations.AddField(
            model_name='metas',
            name='Caja9Litros',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
