# Generated by Django 5.0.6 on 2024-07-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0019_metas_caja9litros'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='clave',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedores',
            name='estatus',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedores',
            name='rfc',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
