# Generated by Django 5.0.6 on 2024-07-31 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0020_proveedores_clave_proveedores_estatus_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Metas',
        ),
    ]
