# Generated by Django 5.0.6 on 2024-07-31 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0021_delete_metas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.art')),
                ('Canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.canal')),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.proveedores')),
                ('FechaInicio', models.DateTimeField(blank=True, null=True)),
                ('FechaFin', models.DateTimeField(blank=True, null=True)),
                ('Apoyo', models.FloatField()),
                ('Promos', models.FloatField(blank=True, null=True)),
                ('Cajas', models.FloatField()),
                ('Inversion', models.FloatField()),
                ('PromoPrecio', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('Descuento', models.FloatField()),
                ('Caja9Litros', models.FloatField()),
            ],
        ),
    ]
