# Generated by Django 5.0.6 on 2024-08-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0023_empresagrupo_sucursal_empresa_mov_ventatcalc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VentaTCalc',
        ),
    ]
