# Generated by Django 5.0.6 on 2024-08-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0024_delete_ventatcalc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mov',
        ),
    ]
