# Generated by Django 5.0.6 on 2024-08-07 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0026_mov_ventatcalc_mov_primov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventatcalc',
            name='MovID',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.mov'),
        ),
    ]
