# Generated by Django 5.0.6 on 2024-08-07 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0027_alter_ventatcalc_movid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventatcalc',
            name='MovID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.mov'),
        ),
    ]
