# Generated by Django 5.0.6 on 2024-08-08 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0028_alter_ventatcalc_movid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mov',
            name='Sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.sucursal'),
        ),
    ]
