# Generated by Django 5.0.6 on 2024-08-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0030_alter_ventatcalc_agente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventatcalc',
            name='RenglonTipo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
