# Generated by Django 5.0.6 on 2024-08-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0032_alter_ventatcalc_tipoimpuesto2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventatcalc',
            name='TipoImpuesto3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
