# Generated by Django 5.0.6 on 2024-08-08 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0034_artexistencianeta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtExistenciaNeta',
        ),
    ]
