# Generated by Django 5.0.6 on 2024-08-08 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0035_delete_artexistencianeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtExistenciaNeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.empresa')),
                ('Articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.art')),
                ('Almacen', models.CharField(max_length=10)),
                ('Moneda', models.CharField(max_length=10)),
                ('Existencia', models.FloatField()),
            ],
        ),
    ]
