# Generated by Django 5.0.6 on 2024-08-08 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0037_delete_artexistencianeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtExistenciaNeta',
            fields=[
                ('Almacen', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.empresa')),
                ('Articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.art')),
                ('Moneda', models.CharField(max_length=10)),
                ('Existencia', models.FloatField()),                
            ],
        ),
    ]
