# Generated by Django 5.0.6 on 2024-08-08 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0038_artexistencianeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventatcalc',
            name='Almacen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.artexistencianeta'),
        ),
    ]
