# Generated by Django 5.0.6 on 2024-08-08 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0039_alter_ventatcalc_almacen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventatcalc',
            old_name='Empresa',
            new_name='Empresa_id',
        ),
        migrations.RenameField(
            model_name='ventatcalc',
            old_name='Sucursal',
            new_name='Sucursal_id',
        ),
    ]
