# Generated by Django 5.0.6 on 2024-08-08 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0040_rename_empresa_ventatcalc_empresa_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventatcalc',
            name='Empresa_id',
        ),
        migrations.RemoveField(
            model_name='ventatcalc',
            name='Sucursal_id',
        ),
    ]
