# Generated by Django 5.0.6 on 2024-08-08 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0041_remove_ventatcalc_empresa_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventatcalc',
            name='Empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.empresa'),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.sucursal'),
        ),
    ]
