# Generated by Django 5.0.6 on 2024-08-08 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0042_ventatcalc_empresa_ventatcalc_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventatcalc',
            name='Empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.empresa'),
        ),
        migrations.AlterField(
            model_name='ventatcalc',
            name='Sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.sucursal'),
        ),
    ]
