# Generated by Django 5.0.6 on 2024-08-08 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0044_alter_ventatcalc_movid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventatcalc',
            name='MovID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.mov'),
        ),
    ]
