# Generated by Django 5.0.6 on 2024-08-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0045_alter_ventatcalc_movid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventatcalc',
            name='Articulo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
