# Generated by Django 5.0.6 on 2024-08-08 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0046_alter_ventatcalc_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventatcalc',
            name='Articulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.art'),
        ),
    ]
