# Generated by Django 5.0.6 on 2024-08-08 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampieriApp', '0048_remove_ventatcalc_agente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventatcalc',
            name='Agente',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='AjusteCosteo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Almacen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.artexistencianeta'),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='AnticipoFacturado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='AnticipoMoneda',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='AnticipoRetencion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='AnticipoTipoCambio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='AnticiposFacturados',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Aplica',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='AplicaID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Articulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.art'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ArticuloNombre',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Cantidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='CantidadEmbarcada',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='CantidadFactor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='CantidadInventario',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='CantidadNeta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='CantidadOrdenada',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='CantidadPendiente',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='CantidadReservada',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Causa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Clase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ClasificacionIEPS',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Cliente',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ClienteNombre',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Codigo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Comision',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Concepto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Condicion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ContUso',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ContUso2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ContUso3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Costo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='CostoActividad',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='CostoActividadTotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='CostoEstandar',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='CostoPEPS',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='CostoPromedio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='CostoReposicion',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='CostoTotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='CostoUEPS',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='DescripcionExtra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='DescuentoLinea',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='DescuentoLineal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='DescuentoLinealSinDL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='DescuentoTipo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='DescuentosTotales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='DescuentosTotalesSinDL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Ejercicio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='EmbarqueEstado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='EnviarA',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Espacio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Estatus',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ExcluirISAN',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Extra',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='FAEPorcentaje',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='FAETotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='FechaConclusion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='FechaEmision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='FechaEntrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='FechaOriginal',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='FechaRegistro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='FechaRequerida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='FormaEnvio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='HoraRequerida',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ImpIncDescuentoLineal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ImpIncDescuentosTotales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ImpIncImporte',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ImpIncPreImporte',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ImpIncPrecio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ImpIncSubTotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Importe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ImporteDescuentoGlobal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ImporteSinDL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ImporteSobrePrecio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ImporteTotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Impuesto1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Impuesto1Total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Impuesto2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Impuesto2Total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Impuesto3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Impuesto3Total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Impuestos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ImpuestosPorcentaje',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ListaPreciosEsp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Mililitro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Moneda',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Mov',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='MovID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.mov'),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='NombreComercial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Observaciones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='OrdenadaFactor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Ordencompra',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='PaisOrigen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Paquetes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='PendienteFactor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Periodo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='PoliticaPrecios',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Posicion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='PreImporteSinDL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Precio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='PrecioLista',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='PrecioSinDL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='PrecioTotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='PresupuestoEsp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Prioridad',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ProvInventario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Proyecto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Referencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Renglon',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='RenglonID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='RenglonSub',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='RenglonTipo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ReservadaFactor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Retencion',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Retencion1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Retencion1Total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Retencion2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Retencion2Total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Retencion3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Retencion3Total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ServicioArticulo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ServicioSerie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Situacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='SituacionFecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='SituacionNota',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='SituacionUsuario',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='SubClase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='SubCuenta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='SubTotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='SubTotalSinDL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SampieriApp.sucursal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='SucursalOrigen',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='SucursalVenta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='SusursalEnviarA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Tarima',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='TipoCambio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='TipoImpuesto1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='TipoImpuesto2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='TipoImpuesto3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='TotalNeto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='UEN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='UltimoCosto',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Unidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Usuario',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='Volumen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatcalc',
            name='ZonaImpuesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
